version: "3.9"
secrets:
  db_password:
    environment: DB_PASS
services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backup:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mysql
      - mongo
      - minio
    secrets:
      - db_password
    environment:
      # S3 / MinIO
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio12345
      AWS_REGION: us-east-1
      S3_BUCKET: backups
      S3_ENDPOINT: http://minio:9000
      S3_FORCE_PATH_STYLE: "true"

      # DB URIs
      #   MYSQL
      MYSQL_HOST: mysql
      MYSQL_PORT: # optional, set to default
      MYSQL_USER: root

      #   POSTGRES
      POSTGRES_HOST: postgres
      POSTGRES_PORT: # optional, set to default
      POSTGRES_USER: postgres

      #   MONGO
      MONGO_HOST: mongo
      MONGO_PORT: # optional, set to default
      MONGO_USER: root

      # Passwords/Secrets
      #   Option 1:
      # MYSQL_PWD: example
      # PGPASSWORD: example
      # MONGO_PASS: example

      #   Option 2(for secrets):
      MYSQL_PASS_FILE: /run/secrets/db_password
      POSTGRES_PASS_FILE: /run/secrets/db_password
      MONGO_PASS_FILE: /run/secrets/db_password

      # App Config
      EXPORT_DIR: /backups
    volumes:
      - ./backups:/backups

volumes:
  minio-data:
  pg-data:
  mysql-data:
  mongo-data:
