version: "3.9"

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backup:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mysql
      - mongo
      - minio
    environment:
      # S3 / MinIO
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio12345
      AWS_REGION: us-east-1
      S3_BUCKET: backups
      S3_ENDPOINT: http://minio:9000
      S3_FORCE_PATH_STYLE: "true"

      # DB URIs
      MYSQL_URI: mysql://root:example@mysql:3306/
      POSTGRES_URI: postgresql://postgres:example@postgres:5432/?sslmode=disable
      MONGO_URI: mongodb://root:example@mongo:27017/?authSource=admin

      EXPORT_DIR: /backups
    

volumes:
  minio-data:
  pg-data:
  mysql-data:
  mongo-data:
